ACTION_TRAIN_DIR = "./save_data/train/actions.npy"
ACTION_VAL_DIR = "./save_data/val/actions.npy"
OBS_TRAIN_DIR = "./save_data/train/obs.npy"
OBS_VAL_DIR = "./save_data/val/obs.npy"
NEXT_OBS_TRAIN_DIR = "./save_data/train/next_obs.npy"
NEXT_OBS_VAL_DIR = "./save_data/val/next_obs.npy"
LATENT_DIM = 48
ACTION_DIM = 2
HIDDEN_SIZE = 256
FLATTEN_DIM = 4608
CKPT_DIR = "./checkpoints/best_checkpoint.pth"
DEVICE = 'cuda'
BATCH_SIZE = 256
TRAIN_BATCH_SIZE = 64
CKPT_LSTM_DIR = './checkpoints/best_lstm_checkpoint.pth'
SAVE_DIR = "./Worldmodel/z_data"
Z_VAL_DIR = "./z_data/val"
Z_DATA_VAL_DIR = "./z_data/val/z.npy"
Z_TRAIN_DIR = "./z_data/train"
Z_DATA_TRAIN_DIR = "./z_data/train/z.npy"
NEXT_Z_TRAIN_DIR = "./z_data/train/next_z.npy"
NEXT_Z_VAL_DIR = "./z_data/val/next_z.npy"
SEQUENCE_LEN = 30
EPOCHS = 500
PATIENCE=20
LR = 1e-4

